// Generated by Apple Swift version 1.2 (swiftlang-602.0.49.6 clang-602.0.49)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
#if __has_feature(nullability)
#  define SWIFT_NULLABILITY(X) X
#else
# if !defined(__nonnull)
#  define __nonnull
# endif
# if !defined(__nullable)
#  define __nullable
# endif
# if !defined(__null_unspecified)
#  define __null_unspecified
# endif
#  define SWIFT_NULLABILITY(X)
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import ObjectiveC;
@import AVFoundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSCoder;

SWIFT_CLASS("_TtC11UXFramework15RecordingRedDot")
@interface RecordingRedDot : UIView
+ (RecordingRedDot * __nonnull)sharedInstance;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)show;
- (void)stop;
- (void)drawRect:(CGRect)rect;
@end


SWIFT_CLASS("_TtC11UXFramework13RecordingView")
@interface RecordingView : UIView
+ (RecordingView * __nonnull)sharedInstance;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)showWithText:(NSString * __nonnull)text;
- (void)setNeedsDisplay;
- (void)drawRect:(CGRect)rect;
@end


SWIFT_CLASS("_TtC11UXFramework15UXTestingCamera")
@interface UXTestingCamera : NSObject
+ (UXTestingCamera * __nonnull)sharedInstance;
- (void)start;
- (void)stop;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSError;
@class NSData;
@class AVCaptureFileOutput;
@class NSURL;

SWIFT_CLASS("_TtC11UXFramework16UXTestingManager")
@interface UXTestingManager : NSObject <AVCaptureFileOutputRecordingDelegate>
+ (UXTestingManager * __nonnull)sharedInstance;
@property (nonatomic) BOOL isHiddingMode;
@property (nonatomic) BOOL isFrontCameraRecording;
@property (nonatomic) BOOL debugMode;
@property (nonatomic, copy) NSString * __nonnull appKey;
- (void)start;
- (void)stop;
- (void)leaveAction;
- (void)backAction;
- (void)terminatedAction;
- (void)customEvent:(NSString * __nonnull)name;
- (void)customEventByName:(NSString * __nonnull)name;
- (void)mergeVideosIfExistRemainingVideos;
- (BOOL)checkIfVideoSegmentsRemains;
- (void)mergeRemainingVideos;
- (void)validAppKey:(NSString * __nonnull)key completion:(void (^ __nonnull)(BOOL))completion failure:(void (^ __nonnull)(NSError * __nonnull))failure;
- (void)uploadVideo:(NSString * __nonnull)key data:(NSData * __nonnull)data duration:(int32_t)duration completion:(void (^ __nonnull)(BOOL))completion;
- (void)uploadFrontCamera:(NSString * __nonnull)videoID data:(NSData * __nonnull)data completion:(void (^ __nonnull)(BOOL))completion;
- (void)uploadEvent:(NSString * __nonnull)eventName startTime:(NSString * __nonnull)startTime videoID:(NSString * __nonnull)videoID completion:(void (^ __nonnull)(BOOL))completion failure:(void (^ __nonnull)(NSError * __nonnull))failure;
- (void)uploadAllEventRecursiveWithVideoID:(NSString * __nonnull)vid completion:(void (^ __nonnull)(void))completion failure:(void (^ __nonnull)(NSError * __nonnull))failure;
- (void)clearEvents;
- (NSDictionary * __nullable)getDictionaryByKey:(NSString * __nonnull)x;
- (NSArray * __null_unspecified)getArrayByKey:(NSString * __nonnull)x;
- (NSArray * __nullable)deleteFirstArrayByKey:(NSString * __nonnull)x;
- (void)writeBool:(BOOL)x withKey:(NSString * __nonnull)withKey;
- (void)writeString:(NSString * __nonnull)x withKey:(NSString * __nonnull)withKey;
- (void)writeArray:(NSArray * __nonnull)x withKey:(NSString * __nonnull)withKey;
- (void)writeDictionary:(NSDictionary * __nonnull)x withKey:(NSString * __nonnull)withKey;
- (BOOL)checkBoolValue:(NSString * __nonnull)key;
- (void)captureOutput:(AVCaptureFileOutput * __null_unspecified)captureOutput didFinishRecordingToOutputFileAtURL:(NSURL * __null_unspecified)outputFileURL fromConnections:(NSArray * __null_unspecified)connections error:(NSError * __null_unspecified)error;
@end

@class UIEvent;

SWIFT_CLASS("_TtC11UXFramework15UXTestingWindow")
@interface UXTestingWindow : UIWindow
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)sendEvent:(UIEvent * __nonnull)event;
- (BOOL)canBecomeFirstResponder;
- (void)motionEnded:(UIEventSubtype)motion withEvent:(UIEvent * __nonnull)event;
- (void)startTesting;
- (void)endTesting;
@end

#pragma clang diagnostic pop
